version: '3.9'
services:
  jupyter:
    container_name: ${CONTAINER_NAME_PREFIX}_jupyter
    image: ${IMAGE_NAME}
    build:
      context: .
      args:
        BRANCH_NAME: ${BRANCH_NAME}
        DIR_NAME: ${DIR_NAME}      
        GITHUB_URI: ${GITHUB_URI}      
      dockerfile: Dockerfile
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - 8888:8888
    depends_on:
      - mongodb
    networks:
      - app-network      
    command:
      - "jupyter"
      - "lab"
      - "--ip=0.0.0.0"
      - "--port=8888"
      - "--no-browser"
      - "--allow-root"
      - "--NotebookApp.token=''"
      - "--NotebookApp.notebook_dir='/app'"      
  mongodb:
    image: mongo:7
    container_name: ${CONTAINER_NAME_PREFIX}_mongodb
    restart: always
    ports:
      - 27017:27017
    networks:
      - app-network      
networks:
  app-network:
    driver: bridge      